services:
  oracle:
    image: gvenzl/oracle-free:latest
    environment:
      ORACLE_PASSWORD: sys_Password1
    ports:
      - 15211:1521
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1 FROM DUAL;' | sqlplus -S system/sys_Password1@localhost:1521/FREEPDB1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10