#!/bin/bash
# Generates versioned docs from git release branches at build time
# Usage: ./scripts/generate-versions.sh
#
# This script reads versions from versions.json (manually managed) and
# generates versioned docs for each. Trunk docs serve as "current" (unreleased).
#
# Version structure:
# - current (trunk): /docs/next - unreleased docs
# - latest release branch: /docs - default docs
# - previous release branches: /docs/v2.0, /docs/v1.11, etc.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WEBSITE_DIR="$(dirname "$SCRIPT_DIR")"
REPO_ROOT="$(dirname "$WEBSITE_DIR")"

echo "Generating versioned docs..."

cd "$REPO_ROOT"

# Read versions from manually managed versions.json
VERSIONS_FILE="$WEBSITE_DIR/versions.json"
if [ ! -f "$VERSIONS_FILE" ]; then
  echo "Error: versions.json not found. Please create it manually."
  echo "Example: [\"2.0.x\", \"1.11.x\", \"1.10.x\"]"
  exit 1
fi

# Parse versions.json and build VERSIONS array
# Format: version_label:git_ref (e.g., "1.11.x:release/1.11")
declare -a VERSIONS=()
while IFS= read -r version_label; do
  # Extract version number from label (e.g., "1.11.x" -> "1.11")
  version_num="${version_label%.x}"
  git_ref="release/$version_num"
  VERSIONS+=("$version_label:$git_ref")
done < <(jq -r '.[]' "$VERSIONS_FILE")

if [ ${#VERSIONS[@]} -eq 0 ]; then
  echo "No versions found in versions.json. Skipping versioned docs generation."
  exit 0
fi

echo "Versions from versions.json: ${VERSIONS[*]}"

# Clean existing versioned docs
rm -rf "$WEBSITE_DIR/versioned_docs"
rm -rf "$WEBSITE_DIR/versioned_sidebars"
mkdir -p "$WEBSITE_DIR/versioned_docs"
mkdir -p "$WEBSITE_DIR/versioned_sidebars"

# Generate versioned docs from git refs
for version_entry in "${VERSIONS[@]}"; do
  version_label="${version_entry%%:*}"
  git_ref="${version_entry##*:}"
  
  echo "Generating docs for $version_label from $git_ref..."
  
  # Try the ref directly first, then with origin/ prefix (for CI environments)
  resolved_ref=""
  if git rev-parse --verify "$git_ref" >/dev/null 2>&1; then
    resolved_ref="$git_ref"
  elif git rev-parse --verify "origin/$git_ref" >/dev/null 2>&1; then
    resolved_ref="origin/$git_ref"
  else
    echo "Error: Git ref '$git_ref' does not exist for version $version_label"
    echo "Make sure the release branch exists: git checkout -b $git_ref && git push origin $git_ref"
    exit 1
  fi
  
  echo "Using resolved ref: $resolved_ref"
  
  version_dir="$WEBSITE_DIR/versioned_docs/version-$version_label"
  mkdir -p "$version_dir"
  
  # Extract docs from the git ref (run from repo root to ensure correct path resolution)
  (cd "$REPO_ROOT" && git archive "$resolved_ref" website/docs) | tar -x -C "$version_dir" --strip-components=2

  # Use trunk tags.yml for all versions (superset of all version-specific tags)
  cp "$WEBSITE_DIR/docs/tags.yml" "$version_dir/tags.yml"

  # Copy sidebars (convert to JSON format for versioned sidebars)
  # For simplicity, we'll create a basic autogenerated sidebar
  cat > "$WEBSITE_DIR/versioned_sidebars/version-$version_label-sidebars.json" << 'EOF'
{
  "docs": [{ "type": "autogenerated", "dirName": "." }],
  "api": [
    "api/overview",
    "api/arrow-flight-sql/index",
    "api/jdbc/index",
    "api/odbc/index",
    "api/auth/index",
    "api/tls/index",
    {
      "type": "category",
      "label": "HTTP",
      "collapsible": true,
      "collapsed": false,
      "items": [{ "type": "autogenerated", "dirName": "api/HTTP" }]
    }
  ]
}
EOF
done

# Apply link fixes to versioned docs
if [ -f "$SCRIPT_DIR/fix-versioned-links.sh" ]; then
  "$SCRIPT_DIR/fix-versioned-links.sh"
fi

echo "Done! Generated versions: ${VERSIONS[*]}"
