#!/bin/bash
# Generates versioned docs from git tags/branches at build time
# Usage: ./scripts/generate-versions.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WEBSITE_DIR="$(dirname "$SCRIPT_DIR")"
REPO_ROOT="$(dirname "$WEBSITE_DIR")"

# Define versions and their corresponding git refs
# Format: "version_label:git_ref"
# The first entry is the default/latest version
# Release branches use the format: release/<major>.<minor>
declare -a VERSIONS=(
  "1.11.x:release/1.11"
  # Add more versions as needed:
  # "1.12.x:release/1.12"
)

# Legacy version uses the trunk branch
LEGACY_REF="trunk"

echo "Generating versioned docs..."

# Clean existing versioned docs
rm -rf "$WEBSITE_DIR/versioned_docs"
rm -rf "$WEBSITE_DIR/versioned_sidebars"
mkdir -p "$WEBSITE_DIR/versioned_docs"
mkdir -p "$WEBSITE_DIR/versioned_sidebars"

# Generate versions.json
VERSIONS_JSON="["
first=true
for version_entry in "${VERSIONS[@]}"; do
  version_label="${version_entry%%:*}"
  if [ "$first" = true ]; then
    first=false
  else
    VERSIONS_JSON+=", "
  fi
  VERSIONS_JSON+="\"$version_label\""
done
VERSIONS_JSON+="]"
echo "$VERSIONS_JSON" > "$WEBSITE_DIR/versions.json"

# Generate versioned docs from git refs
for version_entry in "${VERSIONS[@]}"; do
  version_label="${version_entry%%:*}"
  git_ref="${version_entry##*:}"
  
  echo "Generating docs for $version_label from $git_ref..."
  
  # Try the ref directly first, then with origin/ prefix (for CI environments)
  resolved_ref=""
  if git rev-parse --verify "$git_ref" >/dev/null 2>&1; then
    resolved_ref="$git_ref"
  elif git rev-parse --verify "origin/$git_ref" >/dev/null 2>&1; then
    resolved_ref="origin/$git_ref"
  else
    echo "Error: Git ref '$git_ref' does not exist for version $version_label"
    echo "Make sure the release branch exists: git checkout -b $git_ref && git push origin $git_ref"
    exit 1
  fi
  
  echo "Using resolved ref: $resolved_ref"
  
  version_dir="$WEBSITE_DIR/versioned_docs/version-$version_label"
  mkdir -p "$version_dir"
  
  # Extract docs from the git ref (run from repo root to ensure correct path resolution)
  (cd "$REPO_ROOT" && git archive "$resolved_ref" website/docs) | tar -x -C "$version_dir" --strip-components=2
  
  # Copy sidebars (convert to JSON format for versioned sidebars)
  # For simplicity, we'll create a basic autogenerated sidebar
  cat > "$WEBSITE_DIR/versioned_sidebars/version-$version_label-sidebars.json" << 'EOF'
{
  "docs": [{ "type": "autogenerated", "dirName": "." }],
  "api": [
    "api/overview",
    "api/arrow-flight-sql/index",
    "api/jdbc/index",
    "api/odbc/index",
    "api/auth/index",
    "api/tls/index",
    {
      "type": "category",
      "label": "HTTP",
      "collapsible": true,
      "collapsed": false,
      "items": [{ "type": "autogenerated", "dirName": "api/HTTP" }]
    }
  ]
}
EOF
done

echo "Done! Generated versions: ${VERSIONS[*]}"
