version: v1
kind: Spicepod
name: evals

datasets:
  - from: https://github.com/openai/evals/raw/refs/heads/main/evals/registry/data/tetris/tetris.jsonl
    name: tetris
views:
  - name: small_tetris
    sql: |
      SELECT * FROM tetris LIMIT 50

evals:
  - name: tetris
    dataset: small_tetris
    scorers:
      - match

models:
  - name: my_model
    from: openai:gpt-4o-mini
    params:
      openai_api_key: ${ secrets:SPICE_OPENAI_API_KEY }
